"""Run all the jewels."""

# import os

listicle = ["agscottpruitt", "ajitpaifcc", "andypuzder",
            "citizens_united", "clewandowski_", "coburnforsenate",
            "danscavino", "david_bossie", "donaldjtrumpjr",
            "erictrump", "genflynn", "governorperry",
            "ivankatrump", "jasonmillerindc", "kellyannepolls",
            "larry_kudlow", "linda_mcmahon", "lindseygrahamsc",
            "marcorubio", "michaelcohen212", "monicacrowley",
            "nikkihaley", "pambondi", "petehoekstra",
            "potus", "realbencarson", "realdonaldtrump",
            "reince", "repmikerogers", "reptomprice",
            "rogerjstonejr", "ryanzinke", "sarahpalinusa",
            "scaramucci", "scottpruittok", "seanhannity",
            "seanspicer", "sebgorka", "senatemajldr",
            "sendancoats", "senjohnmccain", "sheriffclarke",
            "speakerryan", "stephenbannon", "tedcruz",
            "vitielloronald", "vp", "whitehouse",
            "hillaryclinton", "richardbspencer", "glennbeck",  # added myself
            "billclinton", "billmaher", "focusfamily",
            "joelosteen", "anncoulter", "betsydevosed",
            "newtgingrich", "patmccrorync", "nra",
            "drjamescdobson", "karlrove", "tomilahren",
            "dwstweets", "tuckercarlson", "tppatriots",
            "heritage", "jerryfalwelljr", "voxday",
            "aigkenham", "frcdc", "cernovich",
            "700club", "michelebachmann", "amrenaissance",
            "jartaylor", "themaddimension", "drdavidduke",
            "white_history", "newrightamerica", "tradyouth",
            "tradworker", "realalexjones", "infowars",
            "seventhsontrs", "sutherlandinst", "sicooke",
            "briansbrown", "heartbeatintl", "baptist4freedom",
            "drbaehr", "movieguide", "matthewbrobbins",
            "am_national", "alvedaking", "priestsforlife",
            "frfrankpavone", "nomupdate", "govmikehuckabee",
            "jimbakkershow", "jim_bakker", "jaybakker",
            "revolution1994", "davidbartonwb", "pastorjohnhagee",
            "lysaterkeurst", "billygraham", "franklin_graham",
            "bryanjfischer", "josephfarah", "ricksantorum",
            "scottadamssays", "aaron_clarey", "rossjeffries",
            "neilstrauss", "mystery3sr", "daviddeangelo",
            "goodlookinglosr", "aurini", "ezralevant",
            "caolanrob", "lauren_southern", "faithgoldy",
            "nigel_farage", "gavin_mcinnes", "broowster",
            "howtobeast", "rationalmale", "stefanmolyneux",
            "sargon_of_akkad", "prisonplanet", "scottmcconnell9",
            "dloesch", "stuntbrain", "worldofstu",
            "conservmillen", "bucksexton", "chrissalcedotx",
            "mattwalshblog", "govchristie", "megynkelly",
            "gopchairwoman", "randpaul", "breitbartnews"]

# ministicle = [  "billoreilly",
#                 "foxnews",
#                 "stevenmnuchin1"
# ]
